# Dependabot Configuration
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "opensourceframework/maintainers"
    labels:
      - "dependencies"
      - "semver:patch"

  - package-ecosystem: "npm"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "opensourceframework/maintainers"
    labels:
      - "dependencies"
      - "semver:patch"